image: averhlv/tc_test:latest

services:
    - mongo:latest

stages:
    - test
    - deploy

all_tests:
    stage: test
    script:
        - bash ./tests.sh

deploy:
    stage: deploy
    only:
        - master
    script:
        - python fabfile.py